= UN document samples in Metanorma (Metanorma-UN)

image:https://github.com/metanorma/mn-samples-un/workflows/generate/badge.svg["Build Status", link="https://github.com/metanorma/mn-samples-un/actions?query=workflow%3Agenerate"]
image:https://github.com/metanorma/mn-samples-un/workflows/docker/badge.svg["Docker Build Status", link="https://github.com/metanorma/mn-samples-un/actions?query=workflow%3Adocker"]

This document is available in its rendered forms here:

* https://metanorma.github.io/mn-samples-un/[UN sample documents (repository)]

== Introduction

This repository provides examples of UN documents encoded in the   https://github.com/metanorma/metanorma-un[Metanorma-UN]
format.

Refer to the https://www.metanorma.com/overview/getting-started/[Metanorma quickstart] for a primer on creating Metanorma-UN documents.

Specific syntax document for Metanorma-UN can be found at: https://www.metanorma.com/author/unece/authoring/[Syntax for writing UN documents using Metanorma].

== Fetching the document

[source,sh]
----
git clone https://github.com/metanorma/mn-samples-un/
----


== Installing Build Tools

See https://www.metanorma.com/overview/getting-started/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker:

[source,sh]
----
docker run -v "$(pwd)":/metanorma -w /metanorma -it metanorma/mn metanorma site generate . -o published -c metanorma.yml
----


== Building The Document

[source,sh]
----
metanorma site generate . -o published -c metanorma.yml
----



== Example documents provided in this repo

=== UNECE Plenary document

* `ECE_TRADE_C_CEFACT_2018_6E.adoc`: Metanorma-UN markup source
for a UNECE Plenary document.


=== UNECE Recommendation

* `ECE_TRADE_437E_Rec42.adoc`: Metanorma-UN markup source
for UNECE Recommendation No. 42.


== Description of generated artifacts

* `{filename}.xml`: Metanorma-UN XML output corresponding to the `{filename}.adoc` source

* `{filename}.html`: Metanorma-UN HTML output corresponding to the `{filename}.adoc` source

