= UNECE document samples in Metanorma (Metanorma-UNECE)

image:https://github.com/metanorma/mn-samples-unece/workflows/publish/badge.svg["Build Status", link="https://github.com/metanorma/mn-samples-unece/actions?workflow=publish"]

This document is available in its rendered forms here:

* https://metanorma.github.io/mn-samples-unece/[UNECE sample documents (repository)]

== Introduction

This repository provides examples of UNECE documents encoded in the   https://github.com/metanorma/metanorma-unece[Metanorma-UNECE]
format.

Refer to the https://www.metanorma.com/overview/getting-started/[Metanorma quickstart] for a primer on creating Metanorma-UNECE documents.

Specific syntax document for Metanorma-UNECE can be found at: https://www.metanorma.com/author/unece/authoring/[Syntax for writing UNECE documents using Metanorma].

== Fetching the document

[source,sh]
----
git clone https://github.com/metanorma/mn-samples-unece/
----


== Installing Build Tools

See https://www.metanorma.com/overview/getting-started/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=1
----

The `Makefile` will automatically choose the proper command to
execute.


== Example documents provided in this repo

=== UNECE Plenary document

* `unece-plenary.adoc`: Metanorma-UNECE markup source
for a UNECE Plenary document.


=== UNECE Recommendation

* `unece-plenary.adoc`: Metanorma-UNECE markup source
for UNECE Recommendation No. 42.


== Description of generated artifacts

* `{filename}.xml`: Metanorma-UNECE XML output corresponding to the `{filename}.adoc` source

* `{filename}.html`: Metanorma-UNECE HTML output corresponding to the `{filename}.adoc` source

