name: generate

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: metanorma/metanorma:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Metanorma with un flavor
        uses: actions-mn/setup@v3
        with:
          installation-method: gem
          extra-flavors: un

      - name: Metanorma generate site
        uses: actions-mn/build-and-publish@v2
        with:
          agree-to-terms: true
          destination: artifact
          artifact-name: ${{ github.event.repository.name }}-${{ runner.os }}
